title: Card Selection
icon: material/cards-playing-outline
description: FGA card selection guide. Learn about face card priority, brave chain optimization, and card shuffle features.
search:
  boost: 2
