name: Bug report
description: Create a report to help us improve
labels: bug

body:
  - type: checkboxes
    id: preparation
    attributes:
      label: Preparation
      description: "Before you open a bug report, you should check the following:"
      options:
        - label: I tested the [latest release](https://github.com/ArthurKun21/FGA-Preview-Build/releases)
          required: true
        - label: I looked at other issues (even the [closed ones](https://github.com/ArthurKun21/FGA-Preview-Build/issues?q=is%3Aissue+is%3Aclosed))
          required: true
  - type: dropdown
    id: server
    attributes:
      label: FGO server
      description: On which server does the problem happen?
      multiple: true
      options:
        - NA
        - BetterFGO NA
        - JP
        - BetterFGO JP
        - CN
        - TW
        - KR
    validations:
      required: true
  - type: input
    id: build
    attributes:
      label: FGA build number
      description: |
        The build number can be found on FGA's main screen at the top, it says BUILD:xxxx.
        
        Entering the number is enough.
      placeholder: "2267"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        
        Include steps to reproduce the error if required.

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: "If it is an app crash go to `Settings` -> `Advanced` -> `Share crash logs`"
  - type: dropdown
    id: android-version
    attributes:
      label: Android version
      options:
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
    validations:
      required: true
  - type: input
    id: screen-size
    attributes:
      label: Screen size
      placeholder: "1280x720"
  - type: input
    id: ram
    attributes:
      label: RAM
      placeholder: 4GB
