title: In-Battle Features
icon: material/gamepad-variant
description: FGA Preview in-battle guide. Understand how automatic battles work, including card selection, skill execution, targeting, and resource management.
search:
  boost: 2