title: Battle Setup
icon: material/sword-cross
description: FGA Preview battle configuration guide. Set up auto-battle, skill commands, support selection, card priority, and material farming.
search:
  boost: 2