nav:
  - Home: index.md
  - App:
    - app/requirements.md
    - Settings:
      - app/appearance.md
      - app/global-battle.md
      - app/storage.md
      - app/advanced.md
    - app/fine-tune.md
    - app/library.md
  - Auto Battle:
    - Configuration:
      - battle-setup/config.md
      - battle-setup/card-priority.md
      - battle-setup/materials.md
      - battle-setup/skill-maker.md
      - battle-setup/support.md
    - How to get started:
      - battle-setup/launcher.md
  - scripts/auto-level-servant.md
  - scripts/auto-level-ce.md
  - scripts/auto-ce-exp-bomb.md
  - scripts/auto-level-skills.md
  - scripts/auto-level-append.md
  - Other Scripts: other-scripts/
  - Changelog: changelog/
