title: Other Scripts
icon: material/script-text
description: Additional FGA Preview scripts including lottery automation, friend point gacha, gift box collection, and support image extraction.
search:
  boost: 1.5