title: Enhancement Scripts
icon: material/arrow-up-bold
description: FGA Preview primary scripts. Learn about the main automated scripts available in FGA Preview, including their features, configurations, and usage instructions.
search:
  boost: 3
hide:
  - navigation