name: test build app

on:
  # Manual triggers
  workflow_dispatch:
  push:
    branches-ignore:
      - main

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  test-build-app:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'ArthurKun21/FGA-Preview'
          token: ${{ secrets.PAT }}
      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@7a9ff16c8c6b7ead5d71c0f1cc61f2703170eade # v1.1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_at }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
          echo "url: ${{ steps.last_release.outputs.url }}"
      - name: Prepare build
        run: |
          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV
          
          echo "FGA_VERSION_CODE=$commit_count" >>${GITHUB_ENV}
          echo "FGA_VERSION_NAME=$current_sha" >>${GITHUB_ENV}

          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^pre-//")
          echo "$prev_commit_count"

          commit_count_diff=$(expr $commit_count - $prev_commit_count)
          echo "$commit_count_diff"

          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)

          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV

          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/Arthurkun21/fga-preview/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV

          ${{ env.COMMIT_LOGS }}