name: test release

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  test-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'ArthurKun21/FGA-Preview'
          token: ${{ secrets.PAT }}
      - name: Prepare build
        run: |
          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV
          
          echo "FGA_VERSION_CODE=$commit_count" >>${GITHUB_ENV}
          echo "FGA_VERSION_NAME=$current_sha" >>${GITHUB_ENV}

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
  
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
    
      - name: Build Android Package
        run: |
          ./gradlew assemblepreview --scan --parallel --no-daemon
      
      - name: Clean up build artifacts
        run: |
          cp app/build/outputs/apk/preview/app-preview.apk fga-preview-${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum fga-preview-${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          tag_name: pre-${{ env.COMMIT_COUNT }}
          name: FGA Preview ${{ env.COMMIT_COUNT }}
          body: |
            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal APK | ${{ env.APK_UNIVERSAL_SHA }} |
          files: |
            fga-preview-${{ env.COMMIT_COUNT }}.apk
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}