title: Support Screen
icon: material/account-supervisor
description: FGA Preview support screen guide. Learn how to configure and use the support selection features in FGA Preview for best experience.
search:
  boost: 1.5